import type { VideoSearchResult, UserSearchResult, OrganizationSearchResult } from '../types/search';

export const mockVideoResults: VideoSearchResult[] = [
  {
    videoId: '550e8400-e29b-41d4-a716-446655440001',
    organizationId: 'org-001',
    organizationName: 'Tech Tutorials Inc',
    organizationType: 'BUSINESS',
    userId: 'user-001',
    userEmail: 'sarah@techtutorials.com',
    userUsername: 'sarah_tech',
    userFullName: 'Sarah Johnson',
    title: 'Introduction to React Hooks - Complete Guide',
    description: 'Learn everything about React Hooks including useState, useEffect, useContext, and custom hooks. Perfect for beginners and intermediate developers.',
    originalFilename: 'react-hooks-tutorial.mp4',
    fileSize: 524288000,
    contentType: 'video/mp4',
    durationSeconds: 1845,
    width: 1920,
    height: 1080,
    uploadStatus: 'COMPLETED',
    processingStatus: 'COMPLETED',
    visibility: 'PUBLIC',
    tags: ['react', 'javascript', 'web-development', 'tutorial'],
    createdAt: '2024-09-15T10:30:00Z',
    updatedAt: '2024-09-15T10:35:00Z',
    searchableText: 'Introduction to React Hooks - Complete Guide Learn everything about React Hooks'
  },
  {
    videoId: '550e8400-e29b-41d4-a716-446655440002',
    organizationId: 'org-002',
    organizationName: 'Creative Studios',
    organizationType: 'CREATIVE',
    userId: 'user-002',
    userEmail: 'mike@creative.com',
    userUsername: 'mike_creative',
    userFullName: 'Mike Chen',
    title: 'Advanced CSS Animations and Transitions',
    description: 'Master CSS animations with keyframes, transforms, and transitions. Build stunning visual effects for your websites.',
    originalFilename: 'css-animations-advanced.mp4',
    fileSize: 387420160,
    contentType: 'video/mp4',
    durationSeconds: 2100,
    width: 1920,
    height: 1080,
    uploadStatus: 'COMPLETED',
    processingStatus: 'COMPLETED',
    visibility: 'PUBLIC',
    tags: ['css', 'web-development', 'animation', 'design'],
    createdAt: '2024-09-20T14:15:00Z',
    updatedAt: '2024-09-20T14:20:00Z',
    searchableText: 'Advanced CSS Animations and Transitions Master CSS animations'
  },
  {
    videoId: '550e8400-e29b-41d4-a716-446655440003',
    organizationId: 'org-001',
    organizationName: 'Tech Tutorials Inc',
    organizationType: 'BUSINESS',
    userId: 'user-003',
    userEmail: 'emma@techtutorials.com',
    userUsername: 'emma_dev',
    userFullName: 'Emma Rodriguez',
    title: 'Building REST APIs with Node.js and Express',
    description: 'Complete course on building scalable RESTful APIs using Node.js, Express, and MongoDB. Includes authentication and deployment.',
    originalFilename: 'nodejs-api-course.mp4',
    fileSize: 671088640,
    contentType: 'video/mp4',
    durationSeconds: 3600,
    width: 1920,
    height: 1080,
    uploadStatus: 'COMPLETED',
    processingStatus: 'COMPLETED',
    visibility: 'PUBLIC',
    tags: ['nodejs', 'express', 'api', 'backend', 'tutorial'],
    createdAt: '2024-09-25T09:00:00Z',
    updatedAt: '2024-09-25T09:05:00Z',
    searchableText: 'Building REST APIs with Node.js and Express Complete course on building scalable RESTful APIs'
  },
  {
    videoId: '550e8400-e29b-41d4-a716-446655440004',
    organizationId: 'org-003',
    organizationName: 'Data Science Academy',
    organizationType: 'EDUCATION',
    userId: 'user-004',
    userEmail: 'alex@datasci.com',
    userUsername: 'alex_data',
    userFullName: 'Alex Kumar',
    title: 'Python for Data Science - Machine Learning Basics',
    description: 'Introduction to machine learning with Python. Learn pandas, numpy, scikit-learn, and build your first ML models.',
    originalFilename: 'python-ml-basics.mp4',
    fileSize: 512000000,
    contentType: 'video/mp4',
    durationSeconds: 2700,
    width: 1920,
    height: 1080,
    uploadStatus: 'COMPLETED',
    processingStatus: 'COMPLETED',
    visibility: 'PUBLIC',
    tags: ['python', 'machine-learning', 'data-science', 'tutorial'],
    createdAt: '2024-09-28T11:45:00Z',
    updatedAt: '2024-09-28T11:50:00Z',
    searchableText: 'Python for Data Science - Machine Learning Basics Introduction to machine learning with Python'
  },
  {
    videoId: '550e8400-e29b-41d4-a716-446655440005',
    organizationId: 'org-002',
    organizationName: 'Creative Studios',
    organizationType: 'CREATIVE',
    userId: 'user-005',
    userEmail: 'lisa@creative.com',
    userUsername: 'lisa_design',
    userFullName: 'Lisa Park',
    title: 'UI/UX Design Principles for Modern Web Apps',
    description: 'Learn fundamental design principles, color theory, typography, and how to create beautiful user interfaces that users love.',
    originalFilename: 'ui-ux-principles.mp4',
    fileSize: 445644800,
    contentType: 'video/mp4',
    durationSeconds: 1920,
    width: 1920,
    height: 1080,
    uploadStatus: 'COMPLETED',
    processingStatus: 'COMPLETED',
    visibility: 'PUBLIC',
    tags: ['ui', 'ux', 'design', 'web-development'],
    createdAt: '2024-10-01T16:30:00Z',
    updatedAt: '2024-10-01T16:35:00Z',
    searchableText: 'UI/UX Design Principles for Modern Web Apps Learn fundamental design principles'
  },
  {
    videoId: '550e8400-e29b-41d4-a716-446655440006',
    organizationId: 'org-001',
    organizationName: 'Tech Tutorials Inc',
    organizationType: 'BUSINESS',
    userId: 'user-001',
    userEmail: 'sarah@techtutorials.com',
    userUsername: 'sarah_tech',
    userFullName: 'Sarah Johnson',
    title: 'TypeScript Fundamentals - From JavaScript to TypeScript',
    description: 'Master TypeScript with this comprehensive guide. Learn types, interfaces, generics, and how to integrate TypeScript into your React projects.',
    originalFilename: 'typescript-fundamentals.mp4',
    fileSize: 598016000,
    contentType: 'video/mp4',
    durationSeconds: 2250,
    width: 1920,
    height: 1080,
    uploadStatus: 'COMPLETED',
    processingStatus: 'COMPLETED',
    visibility: 'PUBLIC',
    tags: ['typescript', 'javascript', 'web-development', 'tutorial'],
    createdAt: '2024-10-02T08:00:00Z',
    updatedAt: '2024-10-02T08:05:00Z',
    searchableText: 'TypeScript Fundamentals - From JavaScript to TypeScript Master TypeScript'
  }
];

export const mockUserResults: UserSearchResult[] = [
  {
    userId: 'user-001',
    email: 'sarah@techtutorials.com',
    username: 'sarah_tech',
    firstName: 'Sarah',
    lastName: 'Johnson',
    fullName: 'Sarah Johnson',
    avatarUrl: null,
    isActive: true,
    createdAt: '2024-01-15T10:00:00Z',
    lastLoginAt: '2024-10-03T09:30:00Z',
    searchableText: 'sarah@techtutorials.com sarah_tech Sarah Johnson'
  },
  {
    userId: 'user-002',
    email: 'mike@creative.com',
    username: 'mike_creative',
    firstName: 'Mike',
    lastName: 'Chen',
    fullName: 'Mike Chen',
    avatarUrl: null,
    isActive: true,
    createdAt: '2024-02-10T14:30:00Z',
    lastLoginAt: '2024-10-02T16:45:00Z',
    searchableText: 'mike@creative.com mike_creative Mike Chen'
  }
];

export const mockOrganizationResults: OrganizationSearchResult[] = [
  {
    organizationId: 'org-001',
    name: 'Tech Tutorials Inc',
    description: 'Leading provider of web development tutorials and courses',
    organizationType: 'BUSINESS',
    visibility: 'PUBLIC',
    plan: 'PREMIUM',
    usedStorageGb: 125.5,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-10-01T12:00:00Z'
  },
  {
    organizationId: 'org-002',
    name: 'Creative Studios',
    description: 'Design and creative content creation',
    organizationType: 'CREATIVE',
    visibility: 'PUBLIC',
    plan: 'BUSINESS',
    usedStorageGb: 87.3,
    createdAt: '2024-02-15T00:00:00Z',
    updatedAt: '2024-09-28T10:30:00Z'
  }
];
